all: time_reads

time_reads : time_reads.c
	gcc -Wall -std=gnu99 -g -o time_reads time_reads.c

write_test_file : write_test_file.c
	gcc -Wall -std=gnu99 -g -o write_test_file write_test_file.c
